<?php

namespace AppBundle\Repository;

/**
 * ServersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServersRepository extends \Doctrine\ORM\EntityRepository
{
}
